title: Personal
email: joaoppsilva@gmail.com
description: >-
  Personal
baseurl: "/main"
url: ""
github_username:  JoaoPPSilva

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

aux_links:
  "GitHub":
    - "//github.com/JoaoPPSilva/main"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-readme-index
