title: git@JoaoPSilva
email: joaoppsilva@gmail.com
description: >-
  Home
baseurl: "/main"
url: ""
github_username:  JoaoPPSilva

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

logo: "/assets/images/vmware-logo1.png"

aux_links:
  "GitHub":
    - "//github.com/JoaoPPSilva/main"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-readme-index

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
